name: tecnodeploy-action
description: "Deploya qualcosa all'interno del sistema di Tecno"
inputs:
  file:
    description: "File da deployare"
    required: true
  destination:
    description: "Destinazione in cui deployare"
    required: true
  key:
    description: "Chiave per deployare"
    required: true
  server:
    description: "Server in cui deployare"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        if [[ "${{ inputs.file }}" = "" ]]; then
           exit 0
        fi
        sudo curl -F "key=${{ inputs.key }}" -F "file=@${{ inputs.file }}" -F "destination=${{ inputs.destination }}" http://${{ inputs.server }}/uploadFile | grep 'successo' &> /dev/null
        if [ $? != 0 ]; then
           exit 1
        fi
      shell: bash
