name: tecnodeploy-action
description: "Deploya qualcosa all'interno del sistema di Tecno"
inputs:
  file:
    description: "File da deployare"
    required: true
  key:
    description: "Chiave per deployare"
    required: true
  server:
    description: "Server in cui deployare"
    required: true
runs:
  using: "composite"
  steps:
    - run: exit 1
      shell: bash