on: [ push ]

jobs:
  test_action:
    runs-on: self-hosted
    name: "Test action"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Test action"
        uses: ./
        id: deploy
        with:
          file: "test.txt"
          key: ${{ secrets.key }}
          server: ${{ secrets.server }}
          destination: "test.txt"